module.exports = {
    zipSplit: require('./zip-split'),
    zipCreate: require('./zip-create'),
    jsonSplit: require('./json-split'),
    fetchImages: require('./fetch-images'),
    randomPosts: require('./random-posts'),
    deletePosts: require('./delete-posts'),
    deletePages: require('./delete-pages'),
    addTags: require('./add-tags'),
    addPreview: require('./add-preview'),
    deleteTags: require('./delete-tags'),
    deleteEmptyTags: require('./delete-empty-tags'),
    findReplace: require('./find-replace'),
    changeAuthor: require('./change-author'),
    changeVisibility: require('./change-visibility'),
    deleteMembers: require('./delete-members'),
    changeRole: require('./change-role'),
    addMemberNewsletterSubscription: require('./add-member-newsletter-subscription'),
    removeMemberNewsletterSubscription: require('./remove-member-newsletter-subscription'),
    deleteStaff: require('./delete-staff'),
    contentStats: require('./content-stats'),
    dedupeMembersCsv: require('./dedupe-members-csv')
};
