import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {mkdtemp, writeFile, rm} from 'node:fs/promises';
import axios from 'axios';
import Promise from 'bluebird';

// Permissive, royalty-free fallbacks used when a download/upload fails.
// Picsum (Unsplash-sourced) for images; lorem.media (Pixabay/Pexels/Internet
// Archive, all free for commercial use) for audio/video.
const PICSUM = 'https://picsum.photos';
const LOREM_MEDIA = 'https://lorem.media';

// Builds a self-contained asset manager. Assets are downloaded from a
// permissive source and re-uploaded to the Ghost site so the seeded content
// does not depend on third-party hotlinks. Results are cached by key so the
// same asset is only fetched and uploaded once.
const createAssetManager = ({api, args = {}, tmpRoot}) => {
    const imageCache = new Map();
    const mediaCache = new Map();
    const fileCache = new Map();
    const assetDelay = args.assetDelay ?? Math.max(args.delayBetweenCalls ?? 50, 250);

    const download = async (url) => {
        const response = await axios.get(url, {
            responseType: 'arraybuffer',
            maxRedirects: 5,
            timeout: 30000
        });
        return Buffer.from(response.data);
    };

    const writeTemp = async (buffer, filename) => {
        const filePath = join(tmpRoot, filename);
        await writeFile(filePath, buffer);
        return filePath;
    };

    // Fetch an image from the configured source and upload it to Ghost.
    // Returns {url, width, height}. Cached by `key`.
    const getImage = async ({key, width = 1200, height = 800}) => {
        if (imageCache.has(key)) {
            return imageCache.get(key);
        }

        let ghostUrl;
        try {
            const sourceUrl = `${PICSUM}/seed/${encodeURIComponent(key)}/${width}/${height}.jpg`;
            const buffer = await download(sourceUrl);
            const filePath = await writeTemp(buffer, `${key}.jpg`);
            const uploaded = await api.images.upload({file: filePath, ref: key});
            ghostUrl = uploaded.url;
            await rm(filePath, {force: true});
            await Promise.delay(assetDelay);
        } catch (error) {
            // Fall back to a hotlinked permissive URL so seeding still succeeds.
            ghostUrl = `${PICSUM}/seed/${encodeURIComponent(key)}/${width}/${height}.jpg`;
        }

        const result = {url: ghostUrl, width, height};
        imageCache.set(key, result);
        return result;
    };

    // Fetch a media asset (audio/video) from lorem.media and upload it to
    // Ghost. Returns {url, mimeType, hotlinked}. Cached by type.
    const getMedia = async ({type}) => {
        if (mediaCache.has(type)) {
            return mediaCache.get(type);
        }

        const sourceUrl = `${LOREM_MEDIA}/${type}`;
        const ext = type === 'audio' ? 'mp3' : 'mp4';
        const mimeType = type === 'audio' ? 'audio/mpeg' : 'video/mp4';
        const purpose = type === 'audio' ? 'audio' : 'video';

        let result;
        try {
            const buffer = await download(sourceUrl);
            const filePath = await writeTemp(buffer, `${type}.${ext}`);
            const uploaded = await api.media.upload({file: filePath, purpose});
            await rm(filePath, {force: true});
            await Promise.delay(assetDelay);
            result = {url: uploaded.url, mimeType, hotlinked: false};
        } catch (error) {
            // lorem.media follows a 302 to a stable CDN URL we can hotlink.
            result = {url: sourceUrl, mimeType, hotlinked: true};
        }

        mediaCache.set(type, result);
        return result;
    };

    // Upload a small placeholder file and return {url, fileName, fileSize}.
    // Used by the Style Guide's file (download) card. Cached by key.
    const getFile = async ({key, fileName = 'placeholder.txt', content}) => {
        if (fileCache.has(key)) {
            return fileCache.get(key);
        }

        const buffer = Buffer.from(content || 'Placeholder document generated by gctools seed-demo.\n', 'utf8');
        let result;
        try {
            const filePath = await writeTemp(buffer, fileName);
            const uploaded = await api.files.upload({file: filePath});
            await rm(filePath, {force: true});
            await Promise.delay(assetDelay);
            result = {url: uploaded.url, fileName, fileSize: buffer.length};
        } catch (error) {
            result = {url: '', fileName, fileSize: buffer.length};
        }

        fileCache.set(key, result);
        return result;
    };

    return {getImage, getMedia, getFile};
};

// Create a temp working directory for downloaded assets.
const createTmpDir = async () => {
    return mkdtemp(join(tmpdir(), 'gctools-seed-'));
};

const cleanupTmpDir = async (dir) => {
    if (dir) {
        await rm(dir, {recursive: true, force: true});
    }
};

export {
    createAssetManager,
    createTmpDir,
    cleanupTmpDir
};
