name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node: ['20.11.1']
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install --ignore-scripts
      - run: yarn test
